name: Test lab5

on:
  push: 
    branches: [main]

  workflow_dispatch:
    inputs:
      action:
        description: "manual"
        required: true
        default: 'flow'
        type: choice
        options:
          - flow

jobs:
  flow:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Install chrome
        run: |
         sudo apt update
         sudo apt install libxss1 libappindicator1 libindicator7 -y
         wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
         sudo apt install ./google-chrome*.deb -y
        
      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'
          
      - name: Create screenshot and html file 
        run: |
          pip install -r requirements.txt
          python3 scenario_2.py

      - name: Archive screenshot artifacts
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: |
            screenshot.png
            
      - name: Archive index artifacts
        uses: actions/upload-artifact@v4
        with:
          name: index
          path: |
            index.html